 # Calcul scientifique -- TP3 -- `numpy`

**Nom :** &nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&ensp; &emsp;    
**Prénom:** &emsp;&emsp;  

Attention: pour ce TP il s'agit d'utiliser numpy et ses fonctionnalités donc pas de bricoler avec des listes et des boucles.

**Il n'y aura pas de boucles dans ce TP**

### 1) Création de tableaux

Pour commencer, on importe la librairie  `numpy`

In [233]:
import numpy as np

Créer une variable numpy de type `array`, nommée `a` contenant les valeurs de 1 à 20 des 3 manières  différentes :

- a1: à partir d'un tableau python  t = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
- a2: en utilisant la fonction arange de numpy
- a3: en utilisant la fonction linspace de numpy

puis afficher le contenu et le type de `a1,a2,a3` pour les 3 méthodes. On doit obtenir le même tableau qu'on appellera ensuite a pour continuer l'exercice.


In [234]:
t = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
# à compléter
a1 = np.array(t)

# la matrice identité d’ordre n
print('a1:',a1,'type :',type(a1))

# à compléter
a2 = np.arange(1, 21, 1)
print('a2:',a2,'type :',type(a2))

# à compléter
a3 = np.linspace(1, 20, 20)
print('a3:',a3,'type :',type(a3))
print(a3.size)

a1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] type : <class 'numpy.ndarray'>
a2: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] type : <class 'numpy.ndarray'>
a3: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.] type : <class 'numpy.ndarray'>
20


In [235]:
ez = np.add(a1, a2)
display(ez)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [236]:
# help(np.linspace)

Calculer puis afficher la somme des valeurs (en une ligne sans faire de boucles) :

In [237]:
# à compléter
np.sum(t)

210

Créer un tableau de taille 20 qu'on appellera b qui contient  20 nombres aléatoires compris entre 1 et 9 inclus.
On utilisera pour cela la fonction `np.random.randint` du module numpy.

In [238]:
# à compléter
b = np.random.randint(1, 10, size=20)
# b = np.random.randint(1, 10, size=(2,3))
display(b)

array([8, 6, 6, 3, 7, 4, 3, 9, 6, 5, 8, 7, 8, 1, 2, 2, 5, 3, 9, 3])

In [239]:
# help(np.random.randint)

Afficher les dimensions de l' `array` `a`, le nombre de valeurs selon chaque dimension (shape) ainsi que sa taille (nombre de valeurs) :

In [240]:
# à compléter

print('ndim= ', a1.ndim,     'shape= ', a1.shape,     'size= ', a1.size)

ndim=  1 shape=  (20,) size=  20


En utilisant uniquement les opérateurs +, / et l'opérateur de tri de numpy (`np.sort()`) et la fonction np.sum(), calculer la moyenne ,  la mediane de `b`,ainsi que les valeurs min et max du tableau. (Ne pas utiliser de boucle).

In [241]:
# à compléter
b_sorted = np.sort(b)

display(b_sorted)

b_moyen = np.sum(b) / b.size
b_mediane = b_sorted[(b.size // 2 )+ 1]

print('moyenne :', b_moyen, 'mediane :', b_mediane)

print('val max :', b_sorted[b.size - 1], 'val min', b_sorted[0])

array([1, 2, 2, 3, 3, 3, 3, 4, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 9, 9])

moyenne : 5.25 mediane : 6
val max : 9 val min 1


Vérifier vos calculs en utilisant les fonctions numpy existantes.

In [242]:
# à compléter

# np.mean() == np.average()

print('moyenne :', np.mean(b), 'mediane :', np.median(b))

print('val max :', np.max(b), 'val min', np.min(b))

moyenne : 5.25 mediane : 5.5
val max : 9 val min 1


Afficher le maximum et l'indice du premier maximum rencontré dans b
Afficher le minimum et l'indice du premier minmum rencontré dans b

In [243]:
# à compléter
print(b)

min_index = list(b).index(np.min(b))
max_index = list(b).index(np.max(b))

display(np.argmin(b))
display(np.argmax(b))

print(f'maxi {np.max(b)} indice {max_index} mini {np.min(b)} indice {min_index}')

[8 6 6 3 7 4 3 9 6 5 8 7 8 1 2 2 5 3 9 3]


13

7

maxi 9 indice 7 mini 1 indice 13


### 2) Opérations vectorisées

Calculer le tableau numpy qu'on appellera tab2 contenant le carré des valeurs de a, sans faire de boucle.

In [244]:
# à compléter
# p = np.full_like(a1, 2)
# np.power(a1, p)

new = np.multiply(a1, a1)
display(new)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

Calculer le tableau tab contenant la somme terme à terme des éléments de a et de a2.

In [245]:
# à compléter

tab = np.add(a1, new)
display(tab)

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156, 182,
       210, 240, 272, 306, 342, 380, 420])

### 3) tableaux multi-dimensions de numpy

Créer un tableau a de taille 6x4 (6 lignes et 4 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus. Vous utiliserez pour cela la fonction `np.random.randint` du module numpy.

Afficher son contenu. 

Le résultat attendu ressemble à ce qui suit, mais les valeurs dépendent bien sûr du tirage au sort :

[[5 1 7 2]\
 [9 3 5 3]\
 [4 9 2 4]\
 [3 2 5 1]\
 [6 2 6 1]\
 [5 5 9 8]]
 
 On fera ensuite afficher dimension, size et shape. 

In [246]:
import numpy as np
# à compléter
tab1 = np.random.randint(1, 10, size=(6,4), dtype=int)
display(tab1)
print('ndim= ', tab1.ndim,     'shape= ', tab1.shape,     'size= ', tab1.size)

array([[6, 6, 8, 7],
       [3, 9, 3, 6],
       [6, 9, 8, 5],
       [8, 6, 5, 1],
       [2, 4, 9, 1],
       [4, 3, 2, 3]])

ndim=  2 shape=  (6, 4) size=  24


#### a) Calculs

Créer une matrice de 3x4 contenant des entiers entre 1 et 9 inclus, puis calculer successivement :

    la somme de toutes les valeurs
    la somme de chacune des lignes
    la somme de chacune des colonnes
    la somme des cubes des valeurs
    

In [247]:
# à compléter
print('Tableau a')
a = np.random.randint(1, 10, size=(3, 4))
display(a)

Tableau a


array([[8, 6, 3, 8],
       [7, 7, 5, 7],
       [1, 3, 5, 8]])

In [248]:
# à compléter
display(np.sum(a))
np.mean(a)

68

5.666666666666667

In [249]:
# à compléter
np.sum(a, axis=0)

array([16, 16, 13, 23])

In [250]:
# à compléter
np.sum(a, axis=1)

array([25, 26, 17])

In [251]:
# à compléter
# vf = np.vectorize(lambda x: x**3)
# new_tab = vf(tab)
# np.sum(new_tab)

np.sum(np.power(a, 3))

3086

Tester la commande
a>=5

En déduire le nombre de valeurs supérieures 5 et la somme des valeurs supérieures 5

In [252]:
# à compléter

print('test a>5:')
# np.place(a, a, a > 5)
res = a > 5
display(res)

test a>5:


array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False, False,  True]])

In [253]:
# à compléter

print('nombre de valeurs supérieures à 5 :')
# np.count_nonzero(a > 5)
np.sum(a > 5)

nombre de valeurs supérieures à 5 :


7

In [254]:
# à compléter)
display(a[a>5])
print('somme des valeurs supérieures à 5 :')
np.sum(a[a>5])


array([8, 6, 8, 7, 7, 7, 8])

somme des valeurs supérieures à 5 :


51

On notera $a_ij$ le contenu de la case (i,j) du tableau a.

Calculer le tableau b tel que $b_ij=a_ij^2+3a_ij -5$

In [255]:
# à compléter
b = np.power(a, 2) + (3 * a) - 5

display(b)

array([[83, 49, 13, 83],
       [65, 65, 35, 65],
       [-1, 13, 35, 83]])

#### b) Indexation

Afficher les valeurs de `tab (fin de la première partie) ` dont les **indices** sont pairs  (attention, les indices pas les valeurs). L'instruction doit être valable pour n'importe quel tableau à 1 dimension, quel que soit le nombre de valeurs.

In [256]:
# à compléter

print('val indices pairs :')
list_index = np.array(range(0, a1.size))
# display(np.argsort(a1))

indices_pairs = a1[list_index % 2 == 0]
display(indices_pairs)

val indices pairs :


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Afficher la somme des valeurs de tab dont les **indices** sont pairs

In [257]:
# à compléter
np.sum(indices_pairs)

100

#### c) Modifications dans un tableau
Créer un tableau `a` de taille 8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus. 

**Pour toutes les questions suivantes, nous travaillerons avec un tableau de taille 8x8  mais vos instructions devraient fonctionner pour un tableau de taille quelconque**

On fera un nouveau tableau par question pour mieux observer les résultats produits.



Au moyen du sélecteur approprié, remplacer toutes les valeurs du tableau par la valeur 0. Attention le nombre de lignes / colonnes doit être conservé. Afficher le résultat.
On doit remplacer les valeurs, pas créer un nouveau tableau.


In [258]:
import numpy as np
# à compléter
a = np.random.randint(1, 10, size=(8,8))
display(a)

# a = np.zeros_like(a)
# a.put(np.array(range(a.size)), 0)
a[:, :] = 0

display(a)

array([[7, 9, 4, 1, 9, 8, 5, 1],
       [5, 8, 1, 9, 2, 7, 8, 8],
       [6, 9, 9, 7, 6, 6, 8, 9],
       [5, 1, 6, 6, 6, 2, 7, 1],
       [3, 1, 4, 7, 9, 2, 9, 1],
       [3, 6, 9, 4, 7, 9, 8, 8],
       [9, 9, 8, 4, 8, 1, 7, 1],
       [9, 4, 2, 5, 5, 2, 5, 6]])

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus,  puis mettre la première ligne du tableau à 0. 


In [259]:
# à compléter
a = np.random.randint(1, 10, size=(8,8))

# list_index_f_line = np.array(range(a.shape[0]))
# a.put(list_index_f_line, 0)

a[0, :] = 0
display(a)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 9, 3, 4, 2, 6, 8, 9],
       [4, 4, 1, 5, 9, 9, 2, 4],
       [1, 7, 5, 5, 3, 6, 1, 1],
       [1, 2, 5, 2, 9, 1, 1, 6],
       [9, 7, 2, 2, 2, 2, 6, 1],
       [9, 9, 4, 8, 9, 1, 4, 8],
       [9, 6, 8, 6, 2, 5, 1, 2]])

Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre la colonne numéro 2 du tableau à 0. 


In [260]:
# à compléter
a = np.random.randint(1, 10, size=(8,8))

a[:, 2] = 0
display(a)

array([[4, 2, 0, 4, 2, 8, 8, 6],
       [4, 5, 0, 9, 2, 2, 1, 1],
       [1, 8, 0, 9, 7, 9, 5, 7],
       [9, 3, 0, 3, 2, 1, 4, 5],
       [2, 5, 0, 3, 6, 9, 1, 1],
       [4, 6, 0, 3, 4, 6, 1, 5],
       [1, 8, 0, 5, 8, 3, 1, 3],
       [8, 3, 0, 9, 4, 3, 3, 8]])

Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus,  puis mettre la première et la dernière colonne à 0 (en une seule instruction)

In [261]:
# à compléter
a = np.random.randint(1, 10, size=(8,8))

a[:, (0, -1)] = 0

display(a)

array([[0, 6, 8, 7, 2, 7, 2, 0],
       [0, 3, 4, 3, 4, 1, 5, 0],
       [0, 3, 6, 1, 5, 2, 3, 0],
       [0, 7, 1, 1, 1, 4, 8, 0],
       [0, 1, 4, 3, 7, 4, 8, 0],
       [0, 5, 9, 9, 8, 4, 5, 0],
       [0, 5, 5, 9, 2, 1, 1, 0],
       [0, 9, 1, 4, 2, 8, 7, 0]])

Créer un tableau `a`de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre les 9 cases de la partie supérieure gauche du tableau à 0 en une seule instruction. 


In [262]:
# à compléter
a = np.random.randint(1, 10, size=(8,8))

a[:3, :3] = 0

display(a)

array([[0, 0, 0, 4, 8, 7, 7, 2],
       [0, 0, 0, 8, 5, 8, 1, 4],
       [0, 0, 0, 9, 9, 6, 1, 9],
       [5, 7, 8, 1, 3, 2, 1, 2],
       [2, 1, 6, 1, 2, 3, 3, 9],
       [4, 7, 6, 6, 2, 6, 9, 9],
       [7, 9, 4, 2, 3, 5, 4, 7],
       [1, 4, 9, 9, 1, 3, 5, 6]])

Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre  les cases qui sont sur des lignes **et** des colonnes paires à 0.

In [263]:
#!TODO à compléter
a = np.random.randint(1, 10, size=(8,8))

# indexs = np.array(range(a.shape[1]))
# display(indexs)
a[::2, ::2] = 0


display(a)

array([[0, 8, 0, 8, 0, 7, 0, 5],
       [5, 4, 5, 3, 2, 1, 8, 3],
       [0, 2, 0, 8, 0, 4, 0, 4],
       [3, 2, 1, 2, 8, 3, 4, 3],
       [0, 7, 0, 3, 0, 5, 0, 8],
       [6, 9, 6, 8, 9, 4, 9, 8],
       [0, 1, 0, 8, 0, 2, 0, 1],
       [2, 6, 4, 8, 1, 9, 5, 6]])

Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre les cases $[1,3]$ et $[3,2]$ à 0 (en une seule instruction). 

In [264]:
# à compléter
a = np.random.randint(1, 10, size=(8,8))

a[1,3] = 0
a[3,2] = 0

display(a)

array([[6, 9, 4, 9, 2, 8, 6, 4],
       [7, 3, 7, 0, 2, 1, 2, 2],
       [2, 7, 7, 5, 5, 8, 6, 8],
       [1, 7, 0, 6, 3, 7, 3, 4],
       [3, 7, 3, 8, 5, 2, 7, 1],
       [5, 1, 3, 9, 6, 9, 2, 8],
       [5, 7, 2, 9, 7, 9, 7, 9],
       [7, 4, 3, 5, 6, 9, 8, 4]])

Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre à 0 toutes les lignes pour lesquelles le vecteur `vect= np.array([False, True, True, False,False, 'True',False, 'True'])` vaut `True` (en une seule instruction). 

In [265]:
# à compléter
a = np.random.randint(1, 10, size=(8,8))

vect= np.array([False, True, True, False,False, True ,False, True])

a[ vect ==True , :] = 0

display(a)

array([[4, 7, 7, 8, 9, 9, 5, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [4, 2, 3, 6, 3, 2, 5, 2],
       [8, 9, 5, 4, 1, 4, 8, 6],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [6, 1, 5, 4, 3, 5, 9, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

A l'aide de la fonction np.ones,  créer un tableau carré de taille 7 ne contenant que des 1.
Puis en maximum deux lignes, faire un "damier" en remplaçant certains 1 par des 0 (voir résultat ci-dessous)

In [266]:
# à compléter

a = np.ones((7,7), dtype= int)

# help(a.flatten)
a = a.flatten()
a[::2] = 0
a = a.reshape(7,7)

display(a)


array([[0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0]])

### 4. Partage de  valeurs dans un tableau

#### a ) " Vues"   (extrait avec des slices) 

Créer un tableau `a` de taille 4x4 rempli de valeurs aléatoires entières de 1 à 9 inclus que l'on nommera a.

Créer ensuite une vue (appelée `b`) de la matrice `a` correspondant aux sélecteurs précédents en prenant pas ar exemple :

    b = a[0,:] 
    
    
Modifier le contenu de `b` et regarder l'effet sur `a`. Puis modifier `a` et regarder l'effet sur `b`

Exemple de ce qui est attendu :

    a= [[6 3 8 1]
     [3 9 4 4]
     [9 5 4 5]
     [4 2 9 8]] 
     b= [6 3 8 1]
    Après modification de la case 0,3 de a (mise à -1) et la case 0,0 de b (mise à 0)     on obtient :
    a= [[ 0  3  8 -1]
     [ 3  9  4  4]
     [ 9  5  4  5]
     [ 4  2  9  8]] 
     b= [ 0  3  8 -1]    

In [267]:
# à compléter
a = np.random.randint(1, 10, size=(4,4))
display(a)
b = a[0, :]
b[0] = 0
display(a)
a[0,0] = 999
display(b)


array([[6, 2, 3, 1],
       [6, 7, 5, 1],
       [5, 9, 2, 9],
       [2, 7, 5, 9]])

array([[0, 2, 3, 1],
       [6, 7, 5, 1],
       [5, 9, 2, 9],
       [2, 7, 5, 9]])

array([999,   2,   3,   1])

#### b) Copies
Reproduire la même expérience, mais cette fois-ci en définissant `b` comme une copie de `a` (et non plus une vue) à l'aide de la fonction copy avec l'instruction a[0,:].copy().
Comparer les résultats.

In [268]:
# à compléter
a = np.random.randint(1, 10, size=(4,4))
display(a)


b = a[0, :].copy()

b[0] = 1111
display(b)
display(a)


a[0,0] = 999
display(a)
display(b)

array([[6, 2, 7, 6],
       [3, 3, 6, 9],
       [1, 8, 4, 8],
       [9, 5, 2, 2]])

array([1111,    2,    7,    6])

array([[6, 2, 7, 6],
       [3, 3, 6, 9],
       [1, 8, 4, 8],
       [9, 5, 2, 2]])

array([[999,   2,   7,   6],
       [  3,   3,   6,   9],
       [  1,   8,   4,   8],
       [  9,   5,   2,   2]])

array([1111,    2,    7,    6])

### 5) Tableaux de tailles différentes

Créer un array numpy nommé `a` de taille 3x3 contenant des valeurs aléatoires entières entre 1 et 9 compris. 

Créer un second array nommé `b` de taille 1x3 également rempli de valeurs aléatoires entières entre 1 et 9 compris.

Créer un troisième array nommé `c` de taille 3x1 également rempli de valeurs aléatoires entières entre 1 et 9 compris.

In [269]:
# à compléter
a = np.random.randint(1, 10, size=(3,3))
b = np.random.randint(1, 10, size=(1,3))
c = np.random.randint(1, 10, size=(3,1))

Ajouter la constante 5 à a, afficher le résultat :

In [270]:
# à compléter
display(a)
display(a + 5)

array([[5, 4, 2],
       [3, 7, 2],
       [3, 7, 9]])

array([[10,  9,  7],
       [ 8, 12,  7],
       [ 8, 12, 14]])

Calculer (a+b). Que représente ce calcul?

Calculer (a+c). Que représente ce calcul?

Afficher b.T

En déduire une façon d'ajouter b à chaque colonne de a

In [277]:
# à compléter
display(a)
display(b)
display(c)

print('a+b :')
display(a + b)

print('a+c :')
display(a + c)

print('b.T :')
display(b.T)

print('a+b.T :')
display(a + b.T)

array([[5, 4, 2],
       [3, 7, 2],
       [3, 7, 9]])

array([[5, 7, 7]])

array([[2],
       [2],
       [8]])

a+b :


array([[10, 11,  9],
       [ 8, 14,  9],
       [ 8, 14, 16]])

a+c :


array([[ 7,  6,  4],
       [ 5,  9,  4],
       [11, 15, 17]])

b.T :


array([[5],
       [7],
       [7]])

a+b.T :


array([[10,  9,  7],
       [10, 14,  9],
       [10, 14, 16]])

Calculer la somme b+c, afficher le résultat et le commenter.

In [279]:
# à compléter

display(b+c)

display(np.sum(b+c))

array([[ 7,  9,  9],
       [ 7,  9,  9],
       [13, 15, 15]])

93